<a href="https://colab.research.google.com/github/sharathsrini/Transformation-and-Rotations/blob/master/Quiz_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import math

In [21]:
# Question 1
a = math.sqrt(2)/2
A = np.matrix([[a, 0, a],[0, 1, 0], [-a, 0, a]])
A_ = np.linalg.det(A)
_A = np.linalg.inv(A)
_A_ = np.transpose(A)
print(A_)
print(_A)
print(_A_)

1.0000000000000002
[[ 0.70710678  0.         -0.70710678]
 [ 0.          1.          0.        ]
 [ 0.70710678  0.          0.70710678]]
[[ 0.70710678  0.         -0.70710678]
 [ 0.          1.          0.        ]
 [ 0.70710678  0.          0.70710678]]


In [0]:
A_

1.0000000000000002

In [0]:
_A


matrix([[ 0.70710678,  0.        , -0.70710678],
        [ 0.        ,  1.        ,  0.        ],
        [ 0.70710678,  0.        ,  0.70710678]])

In [20]:
A = np.matrix([[0.3835, 0.5730, 0.9287], [0.5710, 0.5919, -0.4119], [-1.3954, 0.0217, 1.1105]])
A_ = np.linalg.det(A)
_A = np.linalg.inv(A)
_A_ = np.transpose(A)
print(A_)
print(_A)
print(_A_)

1.0000632084619998
[[ 0.66620107 -0.61612477 -0.78566657]
 [-0.05932649  1.72167591  0.68820785]
 [ 0.83827497 -0.80783509 -0.10018302]]
[[ 0.3835  0.571  -1.3954]
 [ 0.573   0.5919  0.0217]
 [ 0.9287 -0.4119  1.1105]]


In [18]:
A = np.matrix([[0.2120, 0.7743, 0.5963], [0.2120, -0.6321, 0.7454],[0.9540, -0.0316, -0.2981]])
A_ = np.linalg.det(A)
_A = np.linalg.inv(A)
_A_ = np.transpose(A)
print(A_, _A,_A_)

1.0000759581 [[ 0.21196755  0.21195965  0.95401199]
 [ 0.77424999 -0.63201939 -0.0316068 ]
 [ 0.59627891  0.74532479 -0.29813415]] [[ 0.212   0.212   0.954 ]
 [ 0.7743 -0.6321 -0.0316]
 [ 0.5963  0.7454 -0.2981]]
